Movie-analytics: main.o base.o stat.o
	gcc -Wall main.o base.o stat.o -o ../Movie-analytics

main.o:
		gcc -Wall -c main.c

base.o:
	gcc -Wall -c base.c

stat.o:
	gcc -Wall -c stat.c

clean:
	rm *.o ../Movie-analytics
